#!/bin/bash

DEFAULT="\033[0;39m"
GREEN="\033[0;92m"
YELLOW="\033[0;93m"

printf "\t\tMan for makefile\n"
printf "\t\t----------------\n\n"
printf "Proto function  :  make ${GREEN}*${DEFAULT}\n\n"
printf "************************************************************************************************************\n"
printf "* ${GREEN}%-20s${DEFAULT} => ${YELLOW}%-80s${DEFAULT} *\n" "Without params" "Compil all files"
printf "* ${GREEN}%-20s${DEFAULT} => ${YELLOW}%-80s${DEFAULT} *\n" "global_libft_init" "Init lib.a"
printf "* ${GREEN}%-20s${DEFAULT} => ${YELLOW}%-80s${DEFAULT} *\n" "clean_libft" "Clean objects files from lib"
printf "* ${GREEN}%-20s${DEFAULT} => ${YELLOW}%-80s${DEFAULT} *\n" "fclean_libft" "Clean objects files from lib and lib.a"
printf "* ${GREEN}%-20s${DEFAULT} => ${YELLOW}%-80s${DEFAULT} *\n" "re_libft" "Do make fclean_libft and global_libft_init"
printf "* ${GREEN}%-20s${DEFAULT} => ${YELLOW}%-80s${DEFAULT} *\n" "add_libft" "Add file(s) inside the lib's Makefile"
printf "* ${GREEN}%-20s${DEFAULT} => ${YELLOW}%-80s${DEFAULT} *\n" "clean" "Clean objects files fro cub3d"
printf "* ${GREEN}%-20s${DEFAULT} => ${YELLOW}%-80s${DEFAULT} *\n" "fclean" "Clean objects files from cub3d and the exec cub3d"
printf "* ${GREEN}%-20s${DEFAULT} => ${YELLOW}%-80s${DEFAULT} *\n" "re" "Do make fclean and make"
printf "* ${GREEN}%-20s${DEFAULT} => ${YELLOW}%-80s${DEFAULT} *\n" "add" "Add file(s) inside the minishell's Makefile"
printf "* ${GREEN}%-20s${DEFAULT} => ${YELLOW}%-80s${DEFAULT} *\n" "man" "Print man"
printf "* ${GREEN}%-20s${DEFAULT} => ${YELLOW}%-80s${DEFAULT} *\n" "fclean_all" "fclean in lib and in srcs"
printf "* ${GREEN}%-20s${DEFAULT} => ${YELLOW}%-80s${DEFAULT} *\n" "bonus" "add move mouse"
printf "************************************************************************************************************\n"